modLoader="javafml"
loaderVersion="${loader_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_ver}"
displayName="${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="logo.png"
#credits=""
authors="${mod_authors}"
#displayTest="MATCH_VERSION"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${fg_range}"
    ordering="NONE"
    side="SERVER"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${mc_range}"
    ordering="NONE"
    side="SERVER"
